version: '3.8'

services:
  backend:
    build: .
    container_name: translation_startup
    ports:
      - "8000"
    volumes:
      # Прокидаємо локальну папку src у внутрішню папку /app
      - ./src:/app
      # База даних залишається окремо
      - ./data:/app/data
      # Захист venv
      - /app/venv/
    env_file:
      - .env
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
                    
      - backend
  frontend:
    build: ./extension-ui
    ports:
      - "5173:5173"
    volumes:
      - ./extension-ui:/app
      - /app/node_modules
      
